### ISSUE TITLE
alembic migration broken

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/ogn-python#47]
On my laptop with ubuntu + sqlite: no problem. On my mac i get this:

(venv) KonstantinsiMac:ogn konstantin$ alembic upgrade +1
Traceback (most recent call last):
  File "/Users/konstantin/Development/workspace/ogn/venv/bin/alembic", line 11, in <module>
    sys.exit(main())
  File "/Users/konstantin/Development/workspace/ogn/venv/lib/python3.5/site-packages/alembic/config.py", line 450, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/konstantin/Development/workspace/ogn/venv/lib/python3.5/site-packages/alembic/config.py", line 444, in main
    self.run_cmd(cfg, options)
  File "/Users/konstantin/Development/workspace/ogn/venv/lib/python3.5/site-packages/alembic/config.py", line 427, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/Users/konstantin/Development/workspace/ogn/venv/lib/python3.5/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/Users/konstantin/Development/workspace/ogn/venv/lib/python3.5/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/Users/konstantin/Development/workspace/ogn/venv/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/konstantin/Development/workspace/ogn/venv/lib/python3.5/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "alembic/env.py", line 18, in <module>
    ogn_config = importlib.import_module(os.environ['OGN_CONFIG_MODULE'])
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'config'

**Comment by Meisterschueler** [comment]
Here is a [undefined config](https://github.com/glidernet/ogn-python/blob/master/alembic/env.py#L39)

**Comment by kerel-fs** [comment]
Yes, the undefined variable is intended. `sqlalchemy.url` is dynamically set in [line 20](https://github.com/glidernet/ogn-python/blob/master/alembic/env.py#L18) by
```
alembic_config.set_main_option('sqlalchemy.url', ogn_config.SQLALCHEMY_DATABASE_URI)
```

The code fails at [line 18](https://github.com/glidernet/ogn-python/blob/master/alembic/env.py#L18) when it tries to load the the python module `config.default` (unless you explicitly set the environment variable `OGN_CONFIG_MODULE`). Apparently `config/default.py` is not in the current PythonPath on your mac.

You could test this, insert the following code right before the failing line 18:
```
import sys
print(sys.path)
```
