### ISSUE TITLE
Running celery reports No module named 'ogn.collect'

### ISSUE THREAD

**Issue by matburnham** [glidernet/ogn-python#67]
After updating to the flask migration, I can no longer run the celery worker:

```
$ /webapps/ogn/ogn-python/bin/celery -A ogn_python.collect worker --loglevel=INFO
Traceback (most recent call last):
  File "/webapps/ogn/ogn-python/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/loaders/base.py", line 109, in import_default_modules
    return [self.import_task_module(m) for m in self.default_modules]
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/loaders/base.py", line 109, in <listcomp>
    return [self.import_task_module(m) for m in self.default_modules]
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/loaders/base.py", line 89, in import_task_module
    return self.import_from_cwd(module)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/webapps/ogn/ogn-python/lib/python3.5/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/webapps/ogn/ogn-python/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'ogn.collect'
```

**Comment by matburnham** [comment]
That pull request fixes references to ogn.collect in ogn_python/collect/celery.py. I also wonder if config/default.py should be similarly modified?

**Comment by Meisterschueler** [comment]
Hello @matburnham , if you want to see a 'productive' (yet beta) version of ogn-python please contact me via kammermark@gmx.de so I can send you the URL.
