### ISSUE TITLE
import_airports raises an exception on first run

### ISSUE THREAD

**Issue by matburnham** [glidernet/ogn-python#69]
```
$ LANG=C.UTF-8 LC_ALL=C.UTF-8 OGN_CONFIG_MODULE="myconfig.py" FLASK_APP="ogn_python/app.py" FLASK_ENV="development" flask database import_airports tests/SeeYou.cup
Import airports from 'tests/SeeYou.cup'...
Imported 46673 airports.
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f72a8db9a60>
Traceback (most recent call last):
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f72a8db9a60>
Traceback (most recent call last):
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

Haven't had chance to figure out why, but seems to work second time around :-) Indeed, the error is after the import, so it may not even matter.

```
$ LANG=C.UTF-8 LC_ALL=C.UTF-8 OGN_CONFIG_MODULE="myconfig.py" FLASK_APP="ogn_python/app.py" FLASK_ENV="development" flask database import_airports tests/SeeYou.cup
Import airports from 'tests/SeeYou.cup'...
Imported 46673 airports.
```

**Comment by Meisterschueler** [comment]
Hi @matburnham , could you please check if the problem still exist with the current version?

**Comment by matburnham** [comment]
Apologies for delay. I clearly haven't touched this in a while!

Looks good to me with current HEAD 1ec015c:

```
$ OGN_CONFIG_MODULE=myconfig.py FLASK_ENV=development FLASK_APP=ogn_python.py flask database import_airports tests/SeeYou.cup
Import airports from 'tests/SeeYou.cup'...
Imported 46673 airports.
```
