### ISSUE TITLE
Wrong call signature for DbFeeder?

### ISSUE THREAD

**Issue by lkangas** [glidernet/ogn-python#73]
`flask gateway run` stops at this line

https://github.com/glidernet/ogn-python/blob/master/app/commands/gateway.py#L29

`AttributeError: module 'datetime' has no attribute 'utcnow'`

since there's `import datetime` and not `from datetime import datetime`. Also `reference_timestamp` is probably not expecting a function handle?

After looking at what `ogn.parser.parse()` expects, I changed the argument to `reference_timestamp=None`. This gave me 

`TypeError: __init__() got an unexpected keyword argument 'prefix'`

Is this whole line an outdated call to `DbFeeder`, which seems to expect a postfix?

**Comment by lkangas** [comment]
I got it running by modifying the line.

`with DbFeeder(postfix='continuous_import', reference_timestamp=datetime.datetime.utcnow(), auto_update_timestamp=True) as feeder:`

**Comment by Meisterschueler** [comment]
Shame on me... I should rewrite this part. Currently we have one timestamp (datetime) for each beacon. This is computed with the timestamp from the aprs beacon (time only) and a "reference_timestamp". We should store 2 timestamps:

1. for the "receiver view" (this is the current timestamp). Since this timestamp is relevant only for the takeoff/landing calculation, we could revert this timestamp from datetime to time
2. for the "ogn-python view" (datetime.utcnow()). This would be the "main timestamp" for the TimescaleDB. We will gain better performance since all incoming beacons will have consecutive timestamps.

**Comment by matburnham** [comment]
Yep, same issue here:

```
$ flask gateway run
[2020-07-19 11:45:33,969] WARNING in gateway: Start ogn gateway
Traceback (most recent call last):
  File "/webapps/ogn/.virtualenvs/ogn/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/webapps/ogn/.virtualenvs/ogn/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/webapps/ogn/ogn-python/app/commands/gateway.py", line 29, in run
    with DbFeeder(prefix='continuous_import', reference_timestamp=datetime.utcnow, reference_timestamp_autoupdate=True) as feeder:
AttributeError: module 'datetime' has no attribute 'utcnow'

```
Used the same bodge-fix:

```
with DbFeeder(postfix='continuous_import', reference_timestamp=datetime.datetime.utcnow(), auto_update_timestamp=True) as feeder:
```

**Comment by Meisterschueler** [comment]
Became obsolete, code changed
