### ISSUE TITLE
Installation: error on "flask database init"

### ISSUE THREAD

**Issue by CazYokoyama** [glidernet/ogn-python#77]
Installation process stops when I follow "Installation and Setup" in README.md. Here is the commands and its output. What am I missing?

git clone https://github.com/glidernet/ogn-python.git
cd ogn-python
pip3 install -r requirements.txt
sudo apt install -y postgresql-10-postgis-2.4
sudo apt-get install -y redis-server
caz@PyTorch-00:~/ogn-python$ flask database init
Traceback (most recent call last):
  File "/home/caz/.local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/caz/.local/lib/python3.6/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/caz/.local/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/caz/.local/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/caz/.local/lib/python3.6/site-packages/click/core.py", line 1662, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/caz/.local/lib/python3.6/site-packages/click/core.py", line 1709, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/caz/.local/lib/python3.6/site-packages/flask/cli.py", line 542, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/home/caz/.local/lib/python3.6/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/home/caz/.local/lib/python3.6/site-packages/flask/cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "/home/caz/.local/lib/python3.6/site-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/home/caz/.local/lib/python3.6/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/home/caz/ogn-python/app/__init__.py", line 41, in create_app
    register_blueprints(app)
  File "/home/caz/ogn-python/app/__init__.py", line 47, in register_blueprints
    from app.main import bp as bp_main
  File "/home/caz/ogn-python/app/main/__init__.py", line 5, in <module>
    import app.main.routes
  File "/home/caz/ogn-python/app/main/routes.py", line 10, in <module>
    from app.model import Airport, Country, CoverageStatistic, AggregateCoverageStatistic, Sender, TakeoffLanding, Logbook, Receiver, ReceiverRanking, ReceiverStatistic, SenderStatistic, FrequencyScanFile
  File "/home/caz/ogn-python/app/model/__init__.py", line 14, in <module>
    from .logbook import Logbook
  File "/home/caz/ogn-python/app/model/logbook.py", line 6, in <module>
    class Logbook(db.Model):
  File "/home/caz/ogn-python/app/model/logbook.py", line 19, in Logbook
    sender = db.relationship("Sender", foreign_keys=[sender_id], backref=db.backref("logbook_entries", order_by=db.case({True: takeoff_timestamp, False: landing_timestamp}, takeoff_timestamp != db.null()).desc()))
  File "<string>", line 2, in case
  File "/home/caz/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 2866, in __init__
    for (c, r) in whens
  File "/home/caz/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 2866, in <listcomp>
    for (c, r) in whens
  File "/home/caz/.local/lib/python3.6/site-packages/sqlalchemy/sql/coercions.py", line 187, in expect
    element, argname=argname, **kw
  File "/home/caz/.local/lib/python3.6/site-packages/sqlalchemy/sql/coercions.py", line 370, in _literal_coercion
    self._raise_for_expected(element, argname)
  File "/home/caz/.local/lib/python3.6/site-packages/sqlalchemy/sql/coercions.py", line 282, in _raise_for_expected
    util.raise_(exc.ArgumentError(msg, code=code), replace_context=err)
  File "/home/caz/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Column expression expected, got True.

caz@PyTorch-00:~/ogn-python$ more /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by CazYokoyama** [comment]
may be duplicated.

**Comment by Meisterschueler** [comment]
Fixed with d10b474af7672cfe72ae1c47f549d095232e049e
