### ISSUE TITLE
"flask database init" fails on "Requirement.parse('MarkupSafe>=2.0'), {'Jinja2'}"

### ISSUE THREAD

**Issue by CazYokoyama** [glidernet/ogn-python#82]
Thank you for fixing https://github.com/glidernet/ogn-python/issues/77.
I still have installation problem.

git clone https://github.com/glidernet/ogn-python.git
cd ogn-python
pip3 install -r requirements.txt
sudo apt install -y postgresql-12-postgis-3 redis-server python3-sqlalchemy python3-flask
# logout-login
flask database init
Traceback (most recent call last):
  File "/home/caz/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/caz/.local/lib/python3.8/site-packages/flask/cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "/home/caz/.local/lib/python3.8/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/home/caz/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/caz/.local/lib/python3.8/site-packages/click/core.py", line 1662, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/caz/.local/lib/python3.8/site-packages/click/core.py", line 1709, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/caz/.local/lib/python3.8/site-packages/flask/cli.py", line 539, in get_command
    self._load_plugin_commands()
  File "/home/caz/.local/lib/python3.8/site-packages/flask/cli.py", line 535, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (MarkupSafe 1.1.0 (/usr/lib/python3/dist-packages), Requirement.parse('MarkupSafe>=2.0'), {'Jinja2'})

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

You do not touch Jinja2 nor MakupSafe as below. Your  code does not use them too. What am I missing?

caz@ogn-python:~/ogn-python$ git log --grep Jinja2
caz@ogn-python:~/ogn-python$ git log --grep MarkupSafe
caz@ogn-python:~/ogn-python$

**Comment by Meisterschueler** [comment]
Hi, you have an versioning conflict: MarkupSafe 1.1.0 is installed, but >= 2.0 is needed. To prevend this I strongly recommend you to use virtual environments (see installation point 2).

**Comment by CazYokoyama** [comment]
Meisterschueler, I still can not install ogn-python even by virtual environments.  I run the following commands.

git clone https://github.com/glidernet/ogn-python.git
cd ogn-python
python3 -m venv my_environment
source my_environment/bin/activate
pip3 install wheel
pip3 install -r requirements.txt
sudo apt install -y postgresql-all
sudo apt install -y postgresql-10-postgis-2.4 redis-server python3-sqlalchemy python3-flask postgis
export OGN_CONFIG_MODULE="config/my_custom_configuration.py"
flask database init

The last command produces

(my_environment) caz@ogn-python:~/ogn-python$ flask database init
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.
Error: No such command 'database'.

What am I missing?

**Comment by Meisterschueler** [comment]
Sorry, my mistake. You must also set the environment variable "FLASK_APP". I just updated the readme.

**Comment by CazYokoyama** [comment]
Here are commands I run.

sudo apt-get install -y python3-venv
git clone https://github.com/glidernet/ogn-python.git
cd ogn-python
python3 -m venv my_environment
source my_environment/bin/activate
pip3 install wheel
pip3 install -r requirements.txt
sudo apt install -y postgresql-all
sudo apt install -y postgresql-10-postgis-2.4 redis-server python3-sqlalchemy python3-flask postgis
sudo -u postgres psql
create database ogn
create user postgres with encrypted password 'postgres'
grant all privileges on database ogn to postgres
#^D
export OGN_CONFIG_MODULE="config.py"
export FLASK_APP=ogn_python.py
flask database init

I have

....
  File "/home/caz/ogn-python/my_environment/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"

I am glad if you give me an advice for the person who has never administrated a database.

**Comment by Meisterschueler** [comment]
Do you have a postgres database "ogn" and a postgres user "postgres" with the default password "postgres"? If not, you must modify the database connection string in the config.py from `postgresql://postgres:postgres@localhost:5432/ogn` to `postgresql://anotheruser:anotherpassword@localhost:5432/thedatabaseyoulike`

**Comment by CazYokoyama** [comment]
I believe "yes, I have a postgres database ogn and a postgres user postgres with the default password postgres" because you see the following lines in my previous comment.

create database ogn
create user postgres with encrypted password 'postgres'
grant all privileges on database ogn to postgres

I have not error or warning message for those 3 lines.

**Comment by Meisterschueler** [comment]
Hi, it is a little tricky to analyze this problem from remote... could you set a breakpoint to the code line where the errors occures and check if the password is correct?

**Comment by CazYokoyama** [comment]
By the following print line,
```
    dsn = _ext.make_dsn(dsn, **kwargs)
    print("XXX", dsn)
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
```
I have
```
(my_environment) caz@ogn-python:~/ogn-python$ flask database init
XXX host=localhost user=postgres password=postgres port=5432 dbname=ogn
```
This is the expected arguments, correct? So the problem is postgres database side. I wonder whether I configured database correctly by the following lines.
```
sudo -u postgres psql
create database ogn
create user postgres with encrypted password postgres
grant all privileges on database ogn to postgres
#^D
```
These lines are exact typing except for #^D which I type control-D.
